name: CI
on:
  - push
  - pull_request
jobs:
  build-windows:
    runs-on: windows-latest
    steps:
      - uses: actions/checkout@v4
      - uses: dtolnay/rust-toolchain@stable
        with:
          target: x86_64-pc-windows-msvc
          components: rustfmt, clippy
      - uses: Swatinem/rust-cache@v2
        with:
          workspaces: './lib -> target'
      - name: Run clippy
        working-directory: lib
        run: |
          cargo clippy --target x86_64-pc-windows-msvc --all-features --locked -- -D warnings
      - name: Run rustfmt
        working-directory: lib
        run: |
          cargo fmt -- --check
      - name: Run build
        working-directory: lib
        run: |
          cargo build --target x86_64-pc-windows-msvc --locked --release
      - name: Copy Lua with other files and zip
        run: |
          cmd /c build.cmd --ci x86_64-pc-windows-msvc
      - uses: actions/upload-artifact@v3
        with:
          name: Windows build
          path: |
            dist/dmi-editor.aseprite-extension
            dist/dmi-editor.zip
  release:
    runs-on: ubuntu-latest
    needs: build-windows
    if: startsWith(github.ref, 'refs/tags/v')
    steps:
      - uses: actions/checkout@v4
      - uses: actions/download-artifact@v3
        with:
          path: dist
      - uses: softprops/action-gh-release@v1
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
        with:
          draft: true
          prerelease: false
          files: |
            dist/dmi-editor.aseprite-extension
            dist/dmi-editor.zip
